Repository rocknsm/rock, pull requests merged in 2019-04, with the labels that each got.

#416 add docket tag to stenographer role
  playbooks/deploy-rock.yml
Labels: awaiting response

#435 Change static values to variables
  roles/common/tasks/configure.yml
Labels: bug

#436 Remove banner on ssh-config
  bin/rock
Labels: enhancement

#440 Fix the way override vars are included
  playbooks/manage-services.yml
Labels: bug

#442 Add tag for saved objects upload
  roles/kibana/tasks/main.yml
Labels: enhancement
